function [laporan] = buatLaporan (data)
%BUATLAPORAN
 
%  Auto-generated by MATLAB on 26-Jul-2015 17:12:00
 
% Create RptgenML.CReport
laporan = RptgenML.CReport('Description','','isView',false,...
'Format','pdf-fop',...
'Stylesheet','default-fo',...
'FilenameName','laporan',...
'FilenameType','other',...
'DirectoryName','C:\',...
'DirectoryType','other');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
judul = rptgen.cfr_titlepage('Author',...
'I Nyoman Kusuma Wardana','Subtitle','Dibuat Oleh:',...
'Title','Logger Data Sensor');
abstrak = rptgen.cfr_text;
set(judul,'AbstractComp',abstrak);
legalNotice = rptgen.cfr_text;
set(judul,'LegalNoticeComp',legalNotice);
gambarJudul = rptgen.cfr_image('FileName','','MaxViewportSize',[7 9]);
set(judul,'ImageComp',gambarJudul);
setParent(judul,laporan);
 
% Create rptgen.cfr_image
gambarLogo = rptgen.cfr_image('FileName',...
'C:\Users\Kusuma\Documents\MATLAB\logo.png','MaxViewportSize',[7 9]);
setParent(gambarLogo,laporan);
 
% Create rptgen.cfr_table
tabelSensor = rptgen.cfr_table('AllAlign','center','Source',data,...
'TableTitle','Data Sensor');
setParent(tabelSensor,laporan);
 
